apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtestapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: techtestapp
  template:
    metadata:
      labels:
        app: techtestapp
    spec:
      containers:
        - name: techtestapp
          image: techtestapp:latest
          args:
            - serve
          ports:
            - containerPort: 3000

