apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtestapp
  template:
    metadata:
      labels:
        app: techtestapp
    spec:
      containers:
        - name: techtestupdatedb
          image: acrtechtest4.azurecr.io/techtestapp:latest
          args:
            - updatedb
