apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: techtestapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techtestapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80