kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres-storage-class
  labels:
    app: postgres
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: postgres-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi