kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres-storage-class
provisioner: kubernetes.io/azure-disk
allowVolumeExpansion: true
parameters:
  skuName: Standard_LRS
  kind: Managed
  cachingmode: None

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: postgres-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi